replicaCount: 1
terminationGracePeriodSeconds: 180
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

# enable this only once - when your blockchain is empty. It overwrites everything
init_genesis: true

explorer:
  name: bsc-explorer
  image:
    repository: mvandep3/bsc-explorer
    tag: latest
    pullPolicy: Always
  service:
    type: ClusterIP
    ports: 
    - name: http
      port: 4000

bsc:
  chain: testnet
  syncmode: "fast"
  gcmode: "archive"
  base_path: "/data"
  httpApi: "db,eth,net,web3,personal,txpool,parlia"
  httpVhosts: "*"
  wsApi: "net,web3,eth"
  wsOrigins: "*"
  maxpeers: 50
  cache: 4096
  image:
    repository: mvandep3/bsc
    tag: latest
    pullPolicy: Always

livenessProbe:
  initialDelaySeconds: 300
  periodSeconds: 300
  timeoutSeconds: 10
  successThreshold: 1
  failureThreshold: 2

service:
  type: ClusterIP
  httpPortName: &httpPortName jsonhttp
  httpPort: &httpPort 8575
  wsPort: &wsPort 8576
  wsPortName: &wsPortName web-socket
  p2pPort0: &p2pPort0 30311
  p2pPortName0: &p2pPortName0 p2p
  p2pPortProtocol0: &p2pPortProtocol0 TCP
  p2pPort1: &p2pPort1 30311
  ports:
    - port: *httpPort
      name: *httpPortName
    - port: *wsPort
      name: *wsPortName
    - port: *p2pPort0
      name: *p2pPortName0
      protocol: *p2pPortProtocol0

bscCmdOverride: false
bscCmd: ""

persistence:
  azure: true
  storageClass: "managed-premium" #or standard
  accessMode: ReadWriteOnce
  size: "1000Gi"

ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: bsc-basic-auth
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required - ok"
  hosts:
    - host: bsc.local
  tls: []

http_auth:
  user: bsc
  password: bsc

resources:
  requests:
    cpu: "1000m"
    memory: "3000Mi"
  limits:
    cpu: "2000m"
    memory: "5000Mi"

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

rootSecurityContext:
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0


nodeSelector: {}

tolerations: []

affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: "bsc"
              bsc/chain: "testnet"
          topologyKey: failure-domain.beta.kubernetes.io/zone


